### ISSUE TITLE
서버구축을 위한 indexer의 작동이 제대로 안됩니다.

### ISSUE THREAD

**Issue by moonsuno** [poesis/postcodify#12]
php indexer.php download 명령으로 데이터를 내려받을 시
에러가 나서 살펴보니 아무래도 다운로드 경로에 변화가 있는것 같습니다.

그래서 수동으로 파일을 받아 php indexer.php createdb로 구축을 하려고 하니
로딩되는 도로명코드 목록이 0로 잡히면서 db입력시 에러가 납니다.

에러는 아래와 같습니다.

`Notice: Trying to get property of non-object in /volume1/web/postcodify/lib/classes/indexer/createdb.php on line 638
PHP Notice:  Trying to get property of non-object in /volume1/web/postcodify/lib/classes/indexer/createdb.php on line 638
`

**Comment by kijin** [comment]
juso.go.kr 에서 파일명과 파일 주소를 또 바꿨군요. 경로만 바꿨다면 간단하게 패치가 가능한데, 도로명코드와 광역시도별 파일을 하나로 합쳐서 완전히 구조가 바뀌어 버렸습니다.

새 구조에 맞추어 수정하는 데 다소 시간이 걸릴 것 같으니 일단 기존의 DB 덤프를 사용하시기 바랍니다.

**Comment by moonsuno** [comment]
DB덤프로 서버 구축후 업데이트를 하려니 아래와 같은 에러가 납니다.

(php indexer.php download-updates시 60일 경과 에러가나는데 /lib/classes/download_update.php파일의 63행을 주석처리 한 뒤 강제로 업데이트를 시도한 결과입니다.)

`Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'' in /volume1/web/postcodify/lib/classes/indexer/update.php:546
Stack trace:
#0 /volume1/web/postcodify/lib/classes/indexer/update.php(546): PDOStatement->execute(Array)
#1 /volume1/web/postcodify/lib/classes/indexer/update.php(92): Postcodify_Indexer_Update->load_updates('20161230')
#2 /volume1/web/postcodify/lib/indexer.php(54): Postcodify_Indexer_Update->start(Object(stdClass))
#3 {main}
  thrown in /volume1/web/postcodify/lib/classes/indexer/update.php on line 546
`

**Comment by kijin** [comment]
정상적으로 업데이트된 DB 덤프를 다시 올렸습니다. 마지막으로 덤프를 생성했을 때가 juso.go.kr 데이터 구조가 변경되기 직전이나 직후였나 봅니다.
