### ISSUE TITLE
업데이트 오류 

### ISSUE THREAD

**Issue by natura4917** [poesis/postcodify#17]
```
HP Fatal error:  Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'building_nums' at row 1 in /home/test/address/postcodify/lib/classes/indexer/update.php:528
Stack trace:
#0 /home/test/address/postcodify/lib/classes/indexer/update.php(528): PDOStatement->execute(Array)
#1 /home/test/address/postcodify/lib/classes/indexer/update.php(92): Postcodify_Indexer_Update->load_updates('20210131')
#2 /home/test/address/postcodify/lib/indexer.php(54): Postcodify_Indexer_Update->start(Object(stdClass))
#3 {main}
  thrown in /home/test/address/postcodify/lib/classes/indexer/update.php on line 528

Fatal error: Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'building_nums' at row 1 in /home/test/address/postcodify/lib/classes/indexer/update.php:528
Stack trace:
#0 /home/test/address/postcodify/lib/classes/indexer/update.php(528): PDOStatement->execute(Array)
#1 /home/test/address/postcodify/lib/classes/indexer/update.php(92): Postcodify_Indexer_Update->load_updates('20210131')
#2 /home/test/address/postcodify/lib/indexer.php(54): Postcodify_Indexer_Update->start(Object(stdClass))
#3 {main}
  thrown in /home/test/address/postcodify/lib/classes/indexer/update.php on line 528


```

MYSQL 덤프파일로  DB 불러온후에 

업데이트를 진행하려고 하니  column 관련 오류가 납니다.

git 최신버전 사용하고 있습니다.

**Comment by kijin** [comment]
`building_nums`가 `varchar(120)` 컬럼인데 그것보다 더 긴 데이터가 있는 모양이군요.

`varchar(240)` 정도로 바꾸고 다시 시도해 보시기 바랍니다.

만약 그렇게 해서 해결된다면 기본 제공하는 스키마도 업데이트하도록 하겠습니다.

**Comment by natura4917** [comment]
lib/resources/schema.php 에 building_nums를 240으로 변경하고 해보니 잘되네요 
감사합니다.
